### PR TITLE
VolumeRepo implementations for superset and subsets

### LINKED ISSUE #17: VolumeRepo - implement querying ht_rights
Tests should use a local sqlite database where necessary.  I recommend a lightweight orm be used, e.g. sequel, to handle the connection details.  

This will require a few manual tests to ensure our test db matches production.

### LINKED ISSUE #18: VolumeRepo - implement querying feed_audit
Tests should use a local sqlite database where necessary. I recommend a lightweight orm be used, e.g. sequel, to handle the connection details.

This will require a few manual tests to ensure our test db matches production.

We want to get volumes that have had their content change within some time window.  False positives are okay, false negatives are not.

### PR DESCRIPTION
**Pull request by malakai97**
Resolves #17 
Resolves #18 

This changes the VolumeRepo interface to only have one method, `#changed_between`.  Instead of needing to determine the appropriate method(s) to use, we can now inject the proper implementation into the scheduler: RightsVolumeRepo for subsets, and RightsFeedVolumeRepo for ht_text.

### CODE REVIEW

**Comment by aelkiss** [comment]
I also want to verify that adding additional rows to `ht_rights.attributes` in production wouldn't require updating the fixtures for the tests here - that is, it would only require changing our code if we wanted to add items with those rights attributes to the datasets?

**Comment by malakai97** [comment]
> I also want to verify that adding additional rows to ht_rights.attributes in production wouldn't require updating the fixtures for the tests here - that is, it would only require changing our code if we wanted to add items with those rights attributes to the datasets?

As long as the schema doesn't change, this will continue to work.  We could add items with those new rights attributes to the datasets without modification of RightsVolumeRepo (might require changes to filters, as one would expect).

**Comment by malakai97** [comment]
>- It looks like `FeedBackend` doesn't fetch rights information, so that causes a few issues:
>    - `RightsFeedVolumeRepo` could include duplicate volumes when it merges the sets (one volume with rights info and another without it)
>     - I'm not 100% sure how you're envisioning using the results here (presumably feeding through `Filter`s to determine which sets to add volumes to) but the `Filter`s will never include an item if the rights are missing (perhaps we should add a test for this).

FeedBackend returns namespace+id pairs as an array of hashes.  That data is then fed to RightsVolumeRepo#in, which returns Volumes with complete information.

> - I don't think you need the `sources` or `reasons` table from `ht_rights`. `sources` will eventually go away, and in general it would be good to make this code as resilient to schema changes as possible.

You are correct.  I've changed the `select` to only project those fields we actually use.  It still makes sense to include that part of the schema to exercise this mismatch.  

- `volume_from` in `rights_volume_repo_spec.rb` creates Volumes that have number `right`s and `access_profile`s rather than symbols. Having the integers in there at all is a little bit ugly but probably unavoidable so long as we're mocking out the entire `ht_rights` database..

Nice save.  It is completely possible to avoid having Volumes with magic integer values in them.  I've updated the spec to reflect this, and the implementation to match.

**Comment by malakai97** [comment]
accepting PR with blessing

**Pull request merged**
